"""add_content_field_to_bookmarks

Revision ID: 3b95fdd7da11
Revises: 28d8c85cf1a4
Create Date: 2025-12-23 21:46:25.272004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b95fdd7da11"
down_revision: Union[str, None] = "28d8c85cf1a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookmarks", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookmarks", "content")
    # ### end Alembic commands ###
